### ISSUE TITLE
근접 거리 센서 없이도 타이머가 작동합니다

### ISSUE THREAD

**Issue by ericKwon95** [boostcampwm2023/iOS06-FlipMate#105]
## 버그 발생 환경
- iOS 17.1

## 버그 발생 내용
- 책상에 근접한 상황이 아닌 공중에서 facedown이 되어도 타이머, 진동, 화면 밝기 조절이 작동하고 있어요

**Comment by nemanjabenkovic** [comment]
`handleOrientationChange` 중에 `UIDevice.current.isProximityMonitoringEnabled = deviceOrientation == .faceDown ? true : false` 로 고치면 될 것 같습니다.
그와 별개로, 센서의 on off가 즉각적으로 반응하지 않는 것에서 비롯된 문제같은데 한번 이야기 해봐야될거같아요
