### ISSUE TITLE
DeviceMotionManager 의존성 관리

### ISSUE THREAD

**Issue by leemhyungyu** [boostcampwm2023/iOS06-FlipMate#398]
## Why
현재 싱글톤으로 사용되고 있던 DeviceMotionManager을 필요한 곳에서 의존성을 주입받아 사용할 수 있도록 수정하겠습니다. 

## Todo
- 
-

**Comment by nemanjabenkovic** [comment]
해당 이슈는 싱글톤으로 유지하기로 했습니다.
