### ISSUE TITLE
iOS에서 디바이스 orientation 감지 기능이 동작하지 않는 문제

### ISSUE THREAD

**Issue by ericKwon95** [boostcampwm2023/iOS06-FlipMate#71]
## 버그 발생 환경
- iOS 17.1
- 1d04de3721376d8cc35d3fc0858bdbcd39fb7e73 커밋

## 버그 발생 내용
- 디바이스 방향을 변경해도 notification이 push되지 않는다.
- 시작할 때 Orientation이 변경되지 않은상태에서 근접거리센서로만 화면을 끌 수 있습니다.

**Comment by nemanjabenkovic** [comment]
+ 시작할 때 Orientation이 변경되지 않은상태에서 근접거리센서로만 화면을 끌 수 있습니다.
